---
- name: Setup new machines
  hosts: lai2
  remote_user: tb15
  become: yes
  tasks:

  - name: Install utilis
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - vim
      - tmux
      - docker.io
      - openjdk-11-jdk
      update_cache: yes

  - name: Set hostname
    hostname:
      name: "{{ hostname }}"

  - name: Change hostname in /etc/hosts
    replace:
      path: /etc/hosts
      regexp: "Lenovo"
      replace: "{{ hostname }}"

  - name: Create user admin
    user:
      name: admin
      #mkpasswd --method=sha-512
      password: '$6$4AJSVzfl.IYd$oizWEQbzQ1Yy3j3HCOgUOvz3x8.4yaDZTXgIYNVUlDck4ESZ.QFHiPd86cREsMZ7bHOkTGY1yRVP7EiTSMiDd0'
      groups:
       - docker
       - sudo
      shell: /bin/bash
      state: present

  - name: Create user informatica
    user:
      name: informatica
      password: '$6$Tz5vwsokc5qqwzSB$SawhY5tPTENsqS9JYu0GFTNvHGwJszsw5vAZ7TVf9jt5/zg8X2apN37ipBSOdQUdREgEEPxWBV0G8Zf7qiWV80'
      groups:
       - docker
      shell: /bin/bash
      state: present

  - name: Create user itismeucci
    user:
      name: itismeucci
      password: '$6$5aBTfKvz$zzs1M/1hAwwZPIWBDCU7gPUPkPSwBpSQGJpkifoYr1aOycTBOGBmTm0R5/d0dc7SrqqOiVTj4Gngo/K/iLK.M/'
      shell: /bin/bash
      state: present

  - name: Install eclipse
    community.general.snap:
      name: eclipse
      classic: yes

  - name: Install netbeans
    community.general.snap:
      name: netbeans
      classic: yes

  - name: Disable automatic login
    replace:
      path: /etc/gdm3/custom.conf
      regexp: "AutomaticLoginEnable=True"
      replace: "AutomaticLoginEnable=False"

  - name: Disable suspend on lid close
    replace:
      path: /etc/systemd/logind.conf
      regexp: "#HandleLidSwitch=suspend"
      replace: "HandleLidSwitch=ignore"

  - name: Disable apt auto-upgrades
    replace:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      regexp: "1"
      replace: "0"
