---
# - name: Update and upgrade apt packages
#   apt:
#     upgrade: yes
#     update_cache: yes

- name: Install apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - gimp

# - name: Install snap packages
#   community.general.snap:
#     name: "{{ packages }}"
#     classic: yes
#   vars:
#     packages:
#     - brackets


- name: Copy bracket deb package
  copy:
    src: Brackets-fixed.deb
    dest: /home/admin/Downloads/

- name: Install bracket deb package
  apt: deb="/home/admin/Downloads/Brackets-fixed.deb"
