#!/bin/bash
tar --exclude='/home/informatica/snap' -zcvf  /home/informatica_bak.tar.gz /home/informatica/*
chown lai2:lai2 /home/informatica_bak.tar.gz
chmod 600 /home/informatica_bak.tar.gz
rm -rf /home/informatica
tar zxvf /home/templates/informatica.tar.gz -C /
