---
- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Change hostname in /etc/hosts
  replace:
    path: /etc/hosts
    regexp: "Lenovo"
    replace: "{{ hostname }}"

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Accept virtualbox-ext-pack seen license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: 'true'
    vtype: seen

- name: Accept virtualbox-ext-pack select license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: 'true'
    vtype: select

- name: Install apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - vim
    - git
    - tmux
    - docker.io
    - openjdk-11-jdk
    - maven
    - virtualbox
    - virtualbox-ext-pack
    - silversearcher-ag

- name: Install snap packages
  community.general.snap:
    name: "{{ packages }}"
    classic: yes
  vars:
    packages:
    - brackets
    - eclipse
    - netbeans
    - arduino

- name: Create admin user
  user:
    name: admin
    #mkpasswd --method=sha-512
    password: '$6$4AJSVzfl.IYd$oizWEQbzQ1Yy3j3HCOgUOvz3x8.4yaDZTXgIYNVUlDck4ESZ.QFHiPd86cREsMZ7bHOkTGY1yRVP7EiTSMiDd0'
    shell: /bin/bash
    state: present
    groups:
    - docker
    - sudo
    - vboxusers
    - dialout

- name: Create informatica user
  user:
    name: informatica
    password: '$6$Tz5vwsokc5qqwzSB$SawhY5tPTENsqS9JYu0GFTNvHGwJszsw5vAZ7TVf9jt5/zg8X2apN37ipBSOdQUdREgEEPxWBV0G8Zf7qiWV80'
    shell: /bin/bash
    state: present
    groups:
    - docker
    - vboxusers
    - dialout

- name: Create itismeucci user
  user:
    name: itismeucci
    password: '$6$5aBTfKvz$zzs1M/1hAwwZPIWBDCU7gPUPkPSwBpSQGJpkifoYr1aOycTBOGBmTm0R5/d0dc7SrqqOiVTj4Gngo/K/iLK.M/'
    shell: /bin/bash
    state: present
    groups:
    - vboxusers

- name: Disable automatic login
  replace:
    path: /etc/gdm3/custom.conf
    regexp: "AutomaticLoginEnable=True"
    replace: "AutomaticLoginEnable=False"

- name: Disable suspend on lid close
  replace:
    path: /etc/systemd/logind.conf
    regexp: "#HandleLidSwitch=suspend"
    replace: "HandleLidSwitch=ignore"

- name: Disable apt auto-upgrades
  replace:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: "1"
    replace: "0"

- name: Copy .ssh files on informatica
  copy:
    src: informatica/.ssh
    dest: /home/informatica/
    owner: informatica
    group: informatica
    mode: '0600'

- name: Change chown for .ssh directory on informatica
  file:
    path: /home/informatica/.ssh
    mode: '0700'
    owner: informatica
    group: informatica

- name: Copy .ssh files on admin
  copy:
    src: admin/.ssh
    dest: /home/admin/
    owner: admin
    group: admin
    mode: '0600'

- name: Change chown for .ssh directory on admin
  file:
    path: /home/admin/.ssh
    mode: '0700'
    owner: admin
    group: admin

- name: Disable ssh password
  notify: restart sshd
  replace:
    path: /etc/ssh/sshd_config
    regexp: "#PasswordAuthentication yes"
    replace: "PasswordAuthentication no"

- name: Copy win10.sh script
  copy:
    src: itismeucci/win10.sh
    dest: /home/itismeucci/
    owner: itismeucci
    group: itismeucci
    mode: '0755'

- name: Copy Win10 autostart
  copy:
    src: itismeucci/VBoxManage.desktop
    dest: /home/itismeucci/.config/autostart/
    owner: itismeucci
    group: itismeucci
    mode: '0700'

- name: Create /home/templates directory
  file:
    path: /home/templates
    state: directory
    mode: '0755'
    owner: admin
    group: admin

- name: Install Chrome
  include_role:
    name: pixelart.chrome

- name: Allow users to change WiFi
  notify: restart network-manager
  copy:
    src: 52-wifi-management.pkla
    dest: /etc/polkit-1/localauthority/50-local.d/
    owner: root
    group: root
    mode: '0644'

- name: Setup git config user.name for informatica
  become_user: informatica
  git_config:
    name: user.name
    scope: global
    value: "{{ hostname }}"

- name: Setup git config user.email for informatica
  become_user: informatica
  git_config:
    name: user.email
    scope: global
    value: "{{ hostname }}@itismeucci.com"

- name: Setup git editor for informatica
  become_user: informatica
  git_config:
    name: core.editor
    scope: global
    value: nano

- name: Copy HomeSync script
  copy:
    src: admin/HomeSync
    dest: /home/admin
    owner: admin
    group: admin
    mode: '0755'

- name: Copy FireBirdLogout script
  copy:
    src: admin/FireBirdLogout
    dest: /home/admin
    owner: admin
    group: admin
    mode: '0755'

- name: Copy home_sync.service
  copy:
    src: home_sync.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'

- name: Copy stop_firebird.service
  copy:
    src: stop_firebird.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: '0644'

- name: Enable home_sync service
  systemd:
    name: home_sync
    enabled: yes
    masked: no

- name: Enable stop_firebird service
  systemd:
    name: stop_firebird
    enabled: yes
    masked: no
