---
- name: Accept virtualbox-ext-pack seen license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: 'true'
    vtype: seen

- name: Accept virtualbox-ext-pack select license
  debconf:
    name: virtualbox-ext-pack
    question: virtualbox-ext-pack/license
    value: 'true'
    vtype: select

- name: Install apt packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - vim
    - tmux
    - docker.io
    - openjdk-11-jdk
    - virtualbox
    - virtualbox-ext-pack
    update_cache: yes

- name: Set hostname
  hostname:
    name: "{{ hostname }}"

- name: Change hostname in /etc/hosts
  replace:
    path: /etc/hosts
    regexp: "Lenovo"
    replace: "{{ hostname }}"

- name: Create user admin
  user:
    name: admin
    #mkpasswd --method=sha-512
    password: '$6$4AJSVzfl.IYd$oizWEQbzQ1Yy3j3HCOgUOvz3x8.4yaDZTXgIYNVUlDck4ESZ.QFHiPd86cREsMZ7bHOkTGY1yRVP7EiTSMiDd0'
    groups:
     - docker
     - sudo
    shell: /bin/bash
    state: present

- name: Create user informatica
  user:
    name: informatica
    password: '$6$Tz5vwsokc5qqwzSB$SawhY5tPTENsqS9JYu0GFTNvHGwJszsw5vAZ7TVf9jt5/zg8X2apN37ipBSOdQUdREgEEPxWBV0G8Zf7qiWV80'
    groups:
     - docker
    shell: /bin/bash
    state: present

- name: Create user itismeucci
  user:
    name: itismeucci
    password: '$6$5aBTfKvz$zzs1M/1hAwwZPIWBDCU7gPUPkPSwBpSQGJpkifoYr1aOycTBOGBmTm0R5/d0dc7SrqqOiVTj4Gngo/K/iLK.M/'
    shell: /bin/bash
    state: present

- name: Install eclipse
  community.general.snap:
    name: eclipse
    classic: yes

- name: Install netbeans
  community.general.snap:
    name: netbeans
    classic: yes

- name: Install brackets
  community.general.snap:
    name: brackets
    classic: yes

- name: Disable automatic login
  replace:
    path: /etc/gdm3/custom.conf
    regexp: "AutomaticLoginEnable=True"
    replace: "AutomaticLoginEnable=False"

- name: Disable suspend on lid close
  replace:
    path: /etc/systemd/logind.conf
    regexp: "#HandleLidSwitch=suspend"
    replace: "HandleLidSwitch=ignore"

- name: Disable apt auto-upgrades
  replace:
    path: /etc/apt/apt.conf.d/20auto-upgrades
    regexp: "1"
    replace: "0"

- name: Copy .ssh files on informatica
  copy:
    src: informatica/.ssh
    dest: /home/informatica/
    owner: informatica
    group: informatica
    mode: '0600'

- name: Change chown for .ssh directory on informatica
  file:
    path: /home/informatica/.ssh
    mode: '0700'
    owner: informatica
    group: informatica

- name: Copy .ssh files on admin
  copy:
    src: admin/.ssh
    dest: /home/admin/
    owner: admin
    group: admin
    mode: '0600'

- name: Change chown for .ssh directory on admin
  file:
    path: /home/admin/.ssh
    mode: '0700'
    owner: admin
    group: admin

- name: Disable ssh password
  replace:
    path: /etc/ssh/sshd_config
    regexp: "#PasswordAuthentication yes"
    replace: "PasswordAuthentication no"
  notify: restart sshd

- name: Copy win10.sh script
  copy:
    src: itismeucci/win10.sh
    dest: /home/itismeucci/
    owner: itismeucci
    group: itismeucci
    mode: '0755'

- name: Create a itismeucci admin autostart directory
  file:
    path: /home/itismeucci/.config/autostart/
    state: directory
    owner: itismeucci
    group: itismeucci
    mode: '0700'

- name: Copy Win10 autostart
  copy:
    src: itismeucci/VBoxManage.desktop
    dest: /home/itismeucci/.config/autostart/
    owner: itismeucci
    group: itismeucci
    mode: '0700'

